# Generated by Django 4.1.2 on 2022-11-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='rendimento',
            field=models.CharField(max_length=200),
        ),
    ]
